[package]
name = "genie"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
cosmwasm-std = "1.0.0"
cw20 = "0.13.4"
cw721 = "0.17.0"
cw-ownable = "0.5.1"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
cosmwasm-schema = { version = "1.0.0" }


[dev-dependencies]
